//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Resources.ErrorMessageResource", typeof(ErrorMessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} تکراری میباشد..
        /// </summary>
        public static string DuplicateItemError {
            get {
                return ResourceManager.GetString("DuplicateItemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} فقط میتواند شامل کاراکتر و اعداد انگلیسی باشد..
        /// </summary>
        public static string EnglishAlphaNumericError {
            get {
                return ResourceManager.GetString("EnglishAlphaNumericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول {0} باید {1} کاراکتر باشد..
        /// </summary>
        public static string FixedLengthError {
            get {
                return ResourceManager.GetString("FixedLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} فقط میتواند شامل اعداد صحیح باشد..
        /// </summary>
        public static string IntegersError {
            get {
                return ResourceManager.GetString("IntegersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت {0} نامعتبر میباشد..
        /// </summary>
        public static string InvalidFormatError {
            get {
                return ResourceManager.GetString("InvalidFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} نامعتبر میباشد..
        /// </summary>
        public static string InvalidItemError {
            get {
                return ResourceManager.GetString("InvalidItemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری یا رمز عبور اشتباه است.
        /// </summary>
        public static string InvalidUserNameOrPasswordError {
            get {
                return ResourceManager.GetString("InvalidUserNameOrPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول {0} باید حداقل {2} و حداکثر {1} کاراکتر باشد..
        /// </summary>
        public static string MinxMaxLengthError {
            get {
                return ResourceManager.GetString("MinxMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} انتخاب نشده است..
        /// </summary>
        public static string NoObjectHasSelected {
            get {
                return ResourceManager.GetString("NoObjectHasSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورودی مورد نظر خالی است.
        /// </summary>
        public static string NullObjectError {
            get {
                return ResourceManager.GetString("NullObjectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} فقط میتواند شامل کاراکترهای عددی باشد..
        /// </summary>
        public static string NumericalCharacterError {
            get {
                return ResourceManager.GetString("NumericalCharacterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} موردنظر وجود ندارد..
        /// </summary>
        public static string ObjectNotFound {
            get {
                return ResourceManager.GetString("ObjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} موردنظر به دلیل ارتباط با موجودیت {1} قابل حذف نیست..
        /// </summary>
        public static string ObjectRelationsDeleteError {
            get {
                return ResourceManager.GetString("ObjectRelationsDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکرار رمز با رمز عبور یکسان نیست..
        /// </summary>
        public static string PasswordConfirmMisMatch {
            get {
                return ResourceManager.GetString("PasswordConfirmMisMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} را وارد نمایید..
        /// </summary>
        public static string RequiredError {
            get {
                return ResourceManager.GetString("RequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} را انتخاب نمایید..
        /// </summary>
        public static string RequiredSelectError {
            get {
                return ResourceManager.GetString("RequiredSelectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول {0} نمیتواند بیشتر از {1} کاراکتر باشد..
        /// </summary>
        public static string StringMaxLengthError {
            get {
                return ResourceManager.GetString("StringMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری غیرفعال است..
        /// </summary>
        public static string UserNotActiveError {
            get {
                return ResourceManager.GetString("UserNotActiveError", resourceCulture);
            }
        }
    }
}
